name: linkus
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.1
  eva_icons_flutter: ^2.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  font_awesome_flutter: ^8.11.0
  google_sign_in: ^4.5.9
  image_picker: ^0.6.7+21
  page_transition: ^1.1.7+6
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: Monteserat
      fonts:
        - asset: assets/fonts/Monteserat.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
